baseurl         = "https://shwetashetye.com"
theme           = "casper-two"
languageCode    = "en-US"
disqusShortname = ""
paginate        = 6
#SectionPagesMenu = "main"

[params]
  title       = "Shweta's Blog"
  subtitle    = "Technical Writer writes"

  cover       = "profilecover.jpg"
  description = "Test; Write; Edit; Repeat!"
  metaDescription = ""
  googleAnalytics = ""
  customCSS = []
  RSSLink = ""

  #twitterName = "faketryghost"
  #fbName = "fakeghost"
  githubName = "shweta345"

  #logo = "prof.jpg"
  orgName = "Shweta Shetye"
  orgWebsite = "https://www.telematika.org"
  orgDescription = "Here is a description placeholder for your org"

  author = "Shweta Shetye"
  authorAvatar = "img/profilepic.jpg"
  authorLocation = "Mumbai, IN"
  authorWebsite = "shweta.shetye.com"
  authorDescription = "Describe yourself.."

  pageNotFoundTitle = "404 - Page not found"

  #casper or caspertwo
  singleViewStyle = "casper"

[permalinks]
  post = "/:slug/"
  about = "/:slug/"

[[menu.main]]
  name = "Main"
  url = "/"
  weight = 200

[[menu.main]]
  name = "Tech"
  url = "/tags/tech/"
  weight = 100

[[menu.main]]
  name = "Life"
  url = "/categories/life/"
  weight = 99

[[menu.main]]
  name = "Parenting"
  url = "/categories/parenting/"
  weight = 99

[[menu.main]]
  name = "About Me"
  url = "/categories/about/"
  weight = 99

[[menu.main]]
  name = "LinkedIn"
  url = "https://linkedin.com/"
  weight = 95